Crm\ClienteBundle\Entity\Cliente:
    type: entity
    table: null
    repositoryClass: Crm\ClienteBundle\Entity\ClienteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        razonSocial:
            type: string
            length: '50'
            column: razon_social
        rfc:
            type: string
            length: '15'
        telefono1:
            type: string
            length: '15'
            column: telefono_1
        ext1:
            type: integer
            column: ext_1
            nullable: TRUE
        telefono2:
            type: string
            length: '15'
            column: telefono_2
            nullable: TRUE
        ext2:
            type: integer
            column: ext_2
            nullable: TRUE
        email:
            type: string
            length: '50'
        paginaWeb:
            type: string
            length: '50'
            column: pagina_web
            nullable: TRUE
        contacto:
            type: string
            length: '125'
            column: contacto
    manyToOne:
        estatus:
           targetEntity: Crm\GeneralBundle\Entity\Estatus
           inversedBy: cliente
           joinColumn:
                name: estatus_id
                referencedColumnName: id
        rangoCliente:
           targetEntity: Crm\ClienteBundle\Entity\RangoCliente
           inversedBy: cliente
           joinColumn:
                name: rangoCliente_id
                referencedColumnName: id
    oneToMany:
        direccionCliente: 
           targetEntity: Crm\ClienteBundle\Entity\DireccionCliente
           mappedBy: Cliente
        venta:
            targetEntity: Crm\VentasBundle\Entity\Venta
            mappedBy: Cliente
    lifecycleCallbacks: {  }
