Crm\EquipoBundle\Entity\Ubicacion:
    type: entity
    table: null
    repositoryClass: Crm\EquipoBundle\Entity\UbicacionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        calle:
            type: string
            length: '50'
        numeroExt:
            type: string
            length: '10'
            column: numero_ext
        numeroInt:
            type: string
            length: '10'
            column: numero_int
            nullable: TRUE
        colonia:
            type: string
            length: '50'
        codigoPostal:
            type: string
            column: codigo_postal
            length: '5'
        localidad:
            type: string
            length: '50'
    manyToOne:
        municipio:
          targetEntity: Crm\GeneralBundle\Entity\Municipio
          inversedBy: ubicacion
          joinColumn:
                name: municipio_id
                referencedColumnName: id
        estado:
          targetEntity: Crm\GeneralBundle\Entity\Estado
          inversedBy: ubicacion
          joinColumn:
                name: estado_id
                referencedColumnName: id
        pais:
          targetEntity: Crm\GeneralBundle\Entity\Pais
          inversedBy: ubicacion
          joinColumn:
                name: pais_id
                referencedColumnName: id
        equipo:
          targetEntity: Crm\EquipoBundle\Entity\Equipo
          inversedBy: ubicacion
          joinColumn:
            name: equipo_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
