cliente_direccioncliente:
    resource: "@ClienteBundle/Resources/config/routing/direccioncliente.yml"
    prefix:   venta/direccioncliente

cliente_cliente:
    resource: "@ClienteBundle/Resources/config/routing/cliente.yml"
    prefix:   venta/cliente

cliente_homepage:
    path:     /hello/{name}
    defaults: { _controller: ClienteBundle:Default:index }
