Crm\ClienteBundle\Entity\Cliente:
    properties:
        razonSocial:
            - NotBlank: { message: "Ingresa la razon social." }
        rfc:
            - NotBlank: { message: "Ingresa RFC." }
            - Regex:
                pattern: "/^[A-Z]{3,4}[0-9]{2}((0{1}[1-9]{1})|(1{1}[0-2]{1}))((0{1}[1-9]{1})|([1-2]{1}[0-9]{1})|(3{1}[0-1]{1}))[A-Z0-9]{3}$/"
                message: El R.F.C. no cuenta con un formato adecuado.
        telefono1:
            - NotBlank: { message: "Ingresa telefono." }
            - Length:
                min: 10
                max: 10
                minMessage: El numero debe de ser de {{ limit }} digitos.
                maxMessage: El numero debe de ser de {{ limit }} digitos.
            - Regex: 
                pattern: "/^[0-9]$/"
                message: Solo digitos.
        ext1:
            - Range:
                min: 1
                max: 5
                minMessage: El numero debe de ser de {{ limit }} digitos o mayor.
                maxMessage: El numero debe de ser de {{ limit }} digitos o menor.
        telefono2:
            - NotBlank: { message: "Ingresa telefono." }
            - Length:
                min: 10
                max: 10
                minMessage: El numero debe de ser de {{ limit }} digitos.
                maxMessage: El numero debe de ser de {{ limit }} digitos.
            - Regex: 
                pattern: '/^[0-9]{10}$/'
                message: Solo digitos.
        ext2:
            - Range:
                min: 1
                max: 5
                minMessage: El numero debe de ser de {{ limit }} digitos o mayor.
                maxMessage: El numero debe de ser de {{ limit }} digitos o menor.
        email:
            - NotBlank: { message: "Ingresa email." }
            - Email:
                message: El email {{ value }} no es válido.
                checkMX: true
        paginaWeb:
            - NotBlank: { message: "Ingresa pagina web." }
        contacto:
            - NotBlank: { message: "Ingresa contacto." }

Crm\ClienteBundle\Entity\DireccionCliente:
    properties:
        calle:
            - NotBlank: { message: "Ingresa calle." }
        numeroExt:
            - NotBlank: { message: "Ingresa numero." }
        colonia:
            - NotBlank: { message: "Ingresa colonia." }
        codigoPostal:
            - NotBlank: { message: "Ingresa codigo Postal." }
            - Range:
                min: 5
                max: 5
                minMessage: El numero debe de ser de {{ limit }} digitos.
                maxMessage: El numero debe de ser de {{ limit }} digitos.
        localidad:
            - NotBlank: { message: "Ingresa localidad." }

Crm\ClienteBundle\Entity\RangoCliente:
    properties:
        rango:
            - NotBlank: { message: "Ingresa un rango." }
        dias:
            - NotBlank: { message: "Ingresa los días de tolerancia" }
            - Range:
                min: 1
                max: 30
                minMessage: El minimo de dias es {{ limit }}.
                maxMessage: El maximo de dias es {{ limit }}.

