Crm\FabricanteBundle\Entity\DireccionFabricante:
    type: entity
    table: null
    repositoryClass: Crm\FabricanteBundle\Entity\DireccionFabricanteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        calle:
            type: string
            length: '50'
        numeroExt:
            type: string
            length: '10'
            column: numero_ext
        numeroInt:
            type: string
            length: '10'
            column: numero_int
        colonia:
            type: string
            length: '50'
        codigoPostal:
            type: string
            column: codigo_postal
            length: '10'
        localidad:
            type: string
            length: '50'
    manyToOne:
        fabricante:
          targetEntity: Crm\FabricanteBundle\Entity\Fabricante
          cascade: [persist]
          inversedBy: direccionFabricante
          joinColumn:
              name: fabricante_id
              referencedColumnName: id
              onDelete: CASCADE
        municipio:
          targetEntity: Crm\GeneralBundle\Entity\Municipio
          inversedBy: direccionFabricante
          joinColumn:
              name: municipio_id
              referencedColumnName: id
        estado:
          targetEntity: Crm\GeneralBundle\Entity\Estado
          inversedBy: direccionFabricante
          joinColumn: 
              name: estado_id
              referencedColumnName: id
        pais:
          targetEntity: Crm\GeneralBundle\Entity\Pais
          inversedBy: direccionFabricante
          joinColumn: 
              name: pais_id
              referencedColumnName: id
    lifecycleCallbacks: {  }
